version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      # all available envs are heidi, heidi-test and heidi-sfx
      - SERVER=${SERVER:-heidi} # Default to 'heidi' if SERVER is not set
    restart: always
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend
      - frontend
      - image-server
      - mxdb-streaming
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./nginx/config:/etc/nginx/conf.d
      - /etc/certificates:/etc/certificates
      - ./nginx/config/nginx.conf.template:/etc/nginx/nginx.conf.template
    networks:
      - my-network

  backend:
    container_name: backend
    image: docker.psi.ch:5000/heidi/backend:${VERSION}
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend/app:/opt/app
      - /etc/mxsecrets.conf:/opt/app/config.yaml
      - /usr/local/mxlibs3:/sls/MX/applications/mxlibs3/all-beamlines/stable
      - /usr/local/mxdbclient:/sls/MX/applications/mxdbclient/all-beamlines/stable
    networks:
      - my-network

  image-server:
    container_name: image-server
    image: docker.psi.ch:5000/heidi/image-server:${VERSION}
    build:
      context: ./image-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8003:8003
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sls/MX/applications/heidi/image_db:/images:ro
    networks:  # Correct indentation here
      - my-network

  mxdb-streaming:
    container_name: mxdb-streaming
    build:
      context: ./mxdb-streaming
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 8008:8008
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/certificates:/etc/certificates:ro
    networks:
      - my-network

  frontend:
    container_name: frontend
    image: docker.psi.ch:5000/heidi/frontend:${VERSION}${SERVER}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # all available envs are heidi, heidi-test and heidi-sfx
        - SERVER=${SERVER:-heidi}  
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - backend
      - image-server
      - mxdb-streaming
    networks:
      - my-network

networks:
  my-network:
